# Generated by Django 4.0.4 on 2022-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='configurable',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Particular',
        ),
    ]
