# Generated by Django 4.0.4 on 2022-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageresource',
            name='name',
        ),
    ]
