# Generated by Django 4.0.4 on 2022-05-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0003_alter_citypair_unique_together'),
        ('hotels', '0003_hotel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_in_city', to='Cities.city'),
            preserve_default=False,
        ),
    ]
