# Generated by Django 4.0.4 on 2022-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tax',
            field=models.FloatField(default=5.0),
        ),
    ]
