# Generated by Django 4.0.4 on 2022-05-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0002_alter_city_options_alter_citypair_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citypair',
            unique_together={('source', 'destination')},
        ),
    ]
