# Generated by Django 4.0.4 on 2022-05-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('Cities', '0002_alter_city_options_alter_citypair_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_point', models.TextField()),
                ('dropping_point', models.TextField()),
                ('pricing', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_city', to='Cities.citypair')),
            ],
        ),
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pivot_bus', to='buses.bus')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pivot_image', to='hotels.imageresource')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.bustype'),
        ),
    ]
