# Generated by Django 4.0.4 on 2022-05-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0004_state'),
        ('buses', '0002_bus_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_city', to='Cities.city'),
        ),
    ]
