# Generated by Django 4.0.4 on 2022-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_bus_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
