# Generated by Django 4.0.4 on 2022-05-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0004_state'),
        ('buses', '0004_bus_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='source',
        ),
        migrations.AddField(
            model_name='bus',
            name='pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bus_city_pair', to='Cities.citypair'),
            preserve_default=False,
        ),
    ]
