# Generated by Django 4.0.4 on 2022-05-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail',
            name='state',
            field=models.CharField(default='CREATED', max_length=255),
            preserve_default=False,
        ),
    ]
