# Generated by Django 4.0.4 on 2022-06-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_orders', '0002_packagedetail_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=55)),
                ('pricing_details', models.TextField()),
                ('markup_details', models.TextField()),
                ('order_details', models.TextField()),
            ],
        ),
    ]
