# Generated by Django 4.0.4 on 2022-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_orders', '0003_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='trip_details',
            field=models.TextField(default=''),
        ),
    ]
